# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_setup(object):
    def setupUi(self, setup):
        setup.setObjectName(_fromUtf8("setup"))
        setup.resize(954, 764)
        self.centralwidget = QtGui.QWidget(setup)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 671, 151))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.axes_lbl_priority = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.axes_lbl_priority.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.axes_lbl_priority.setReadOnly(True)
        self.axes_lbl_priority.setObjectName(_fromUtf8("axes_lbl_priority"))
        self.horizontalLayout_2.addWidget(self.axes_lbl_priority)
        self.axes_lbl_name = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.axes_lbl_name.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.axes_lbl_name.setReadOnly(True)
        self.axes_lbl_name.setObjectName(_fromUtf8("axes_lbl_name"))
        self.horizontalLayout_2.addWidget(self.axes_lbl_name)
        self.axes_lbl_start = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.axes_lbl_start.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.axes_lbl_start.setReadOnly(True)
        self.axes_lbl_start.setObjectName(_fromUtf8("axes_lbl_start"))
        self.horizontalLayout_2.addWidget(self.axes_lbl_start)
        self.axes_lbl_stop = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.axes_lbl_stop.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.axes_lbl_stop.setReadOnly(True)
        self.axes_lbl_stop.setObjectName(_fromUtf8("axes_lbl_stop"))
        self.horizontalLayout_2.addWidget(self.axes_lbl_stop)
        self.axes_lbl_points = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.axes_lbl_points.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.axes_lbl_points.setReadOnly(True)
        self.axes_lbl_points.setObjectName(_fromUtf8("axes_lbl_points"))
        self.horizontalLayout_2.addWidget(self.axes_lbl_points)
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 2)
        self.horizontalLayout_2.setStretch(5, 2)
        self.horizontalLayout_2.setStretch(6, 6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layout_axis_list = QtGui.QVBoxLayout()
        self.layout_axis_list.setSpacing(0)
        self.layout_axis_list.setObjectName(_fromUtf8("layout_axis_list"))
        self.verticalLayout_2.addLayout(self.layout_axis_list)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.axes_btn_add = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.axes_btn_add.setObjectName(_fromUtf8("axes_btn_add"))
        self.horizontalLayout_3.addWidget(self.axes_btn_add)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayoutWidget_11 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 170, 951, 181))
        self.horizontalLayoutWidget_11.setObjectName(_fromUtf8("horizontalLayoutWidget_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.swp_lbl_settings = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_settings.setReadOnly(True)
        self.swp_lbl_settings.setObjectName(_fromUtf8("swp_lbl_settings"))
        self.horizontalLayout.addWidget(self.swp_lbl_settings)
        self.swp_btn_add = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        self.swp_btn_add.setObjectName(_fromUtf8("swp_btn_add"))
        self.horizontalLayout.addWidget(self.swp_btn_add)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.swp_list_settings = QtGui.QListWidget(self.horizontalLayoutWidget_11)
        self.swp_list_settings.setObjectName(_fromUtf8("swp_list_settings"))
        self.verticalLayout_6.addWidget(self.swp_list_settings)
        self.swp_btn_del = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        self.swp_btn_del.setObjectName(_fromUtf8("swp_btn_del"))
        self.verticalLayout_6.addWidget(self.swp_btn_del)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.swp_inp_label = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_label.setObjectName(_fromUtf8("swp_inp_label"))
        self.verticalLayout_7.addWidget(self.swp_inp_label)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.swp_lbl_type = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_type.setReadOnly(True)
        self.swp_lbl_type.setObjectName(_fromUtf8("swp_lbl_type"))
        self.horizontalLayout_8.addWidget(self.swp_lbl_type)
        self.swp_dd_type = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_type.setObjectName(_fromUtf8("swp_dd_type"))
        self.swp_dd_type.addItem(_fromUtf8(""))
        self.swp_dd_type.addItem(_fromUtf8(""))
        self.swp_dd_type.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.swp_dd_type)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.swp_lbl_builtins = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_builtins.setReadOnly(True)
        self.swp_lbl_builtins.setObjectName(_fromUtf8("swp_lbl_builtins"))
        self.verticalLayout_7.addWidget(self.swp_lbl_builtins)
        self.swp_dd_builtins = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_builtins.setObjectName(_fromUtf8("swp_dd_builtins"))
        self.verticalLayout_7.addWidget(self.swp_dd_builtins)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.swp_lbl_vds = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_vds.setReadOnly(True)
        self.swp_lbl_vds.setObjectName(_fromUtf8("swp_lbl_vds"))
        self.verticalLayout_8.addWidget(self.swp_lbl_vds)
        self.swp_dd_vds = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_vds.setObjectName(_fromUtf8("swp_dd_vds"))
        self.verticalLayout_8.addWidget(self.swp_dd_vds)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.swp_lbl_vds_name = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_vds_name.setReadOnly(True)
        self.swp_lbl_vds_name.setObjectName(_fromUtf8("swp_lbl_vds_name"))
        self.horizontalLayout_9.addWidget(self.swp_lbl_vds_name)
        self.swp_inp_vds_name = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_vds_name.setObjectName(_fromUtf8("swp_inp_vds_name"))
        self.horizontalLayout_9.addWidget(self.swp_inp_vds_name)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.swp_lbl_vds_id = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_vds_id.setReadOnly(True)
        self.swp_lbl_vds_id.setObjectName(_fromUtf8("swp_lbl_vds_id"))
        self.horizontalLayout_10.addWidget(self.swp_lbl_vds_id)
        self.swp_inp_vds_id = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_vds_id.setObjectName(_fromUtf8("swp_inp_vds_id"))
        self.horizontalLayout_10.addWidget(self.swp_inp_vds_id)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.swp_lbl_rad = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_rad.setReadOnly(True)
        self.swp_lbl_rad.setObjectName(_fromUtf8("swp_lbl_rad"))
        self.verticalLayout_11.addWidget(self.swp_lbl_rad)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.swp_lbl_rad_server = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_rad_server.setReadOnly(True)
        self.swp_lbl_rad_server.setObjectName(_fromUtf8("swp_lbl_rad_server"))
        self.verticalLayout_9.addWidget(self.swp_lbl_rad_server)
        self.swp_lbl_rad_device = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_rad_device.setReadOnly(True)
        self.swp_lbl_rad_device.setObjectName(_fromUtf8("swp_lbl_rad_device"))
        self.verticalLayout_9.addWidget(self.swp_lbl_rad_device)
        self.swp_lbl_rad_setting = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_rad_setting.setReadOnly(True)
        self.swp_lbl_rad_setting.setObjectName(_fromUtf8("swp_lbl_rad_setting"))
        self.verticalLayout_9.addWidget(self.swp_lbl_rad_setting)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.swp_dd_rad_server = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_rad_server.setObjectName(_fromUtf8("swp_dd_rad_server"))
        self.verticalLayout_10.addWidget(self.swp_dd_rad_server)
        self.swp_dd_rad_device = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_rad_device.setObjectName(_fromUtf8("swp_dd_rad_device"))
        self.verticalLayout_10.addWidget(self.swp_dd_rad_device)
        self.swp_dd_rad_setting = QtGui.QComboBox(self.horizontalLayoutWidget_11)
        self.swp_dd_rad_setting.setObjectName(_fromUtf8("swp_dd_rad_setting"))
        self.verticalLayout_10.addWidget(self.swp_dd_rad_setting)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_14.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.swp_lbl_rad_input_req = QtGui.QTextEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_rad_input_req.setReadOnly(True)
        self.swp_lbl_rad_input_req.setObjectName(_fromUtf8("swp_lbl_rad_input_req"))
        self.horizontalLayout_13.addWidget(self.swp_lbl_rad_input_req)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.swp_lay_rad_inp = QtGui.QVBoxLayout()
        self.swp_lay_rad_inp.setSpacing(0)
        self.swp_lay_rad_inp.setObjectName(_fromUtf8("swp_lay_rad_inp"))
        self.verticalLayout_13.addLayout(self.swp_lay_rad_inp)
        self.swp_btn_rad_set_inputs = QtGui.QPushButton(self.horizontalLayoutWidget_11)
        self.swp_btn_rad_set_inputs.setObjectName(_fromUtf8("swp_btn_rad_set_inputs"))
        self.verticalLayout_13.addWidget(self.swp_btn_rad_set_inputs)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.horizontalLayout_14.setStretch(0, 3)
        self.horizontalLayout_14.setStretch(1, 3)
        self.horizontalLayout_14.setStretch(2, 3)
        self.horizontalLayout_14.setStretch(3, 4)
        self.verticalLayout_21.addLayout(self.horizontalLayout_14)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.swp_lbl_coeff = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff.setReadOnly(True)
        self.swp_lbl_coeff.setObjectName(_fromUtf8("swp_lbl_coeff"))
        self.horizontalLayout_12.addWidget(self.swp_lbl_coeff)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.swp_lbl_coeff_const = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_const.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_const.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_const.setReadOnly(True)
        self.swp_lbl_coeff_const.setObjectName(_fromUtf8("swp_lbl_coeff_const"))
        self.verticalLayout_12.addWidget(self.swp_lbl_coeff_const)
        self.swp_inp_coeff_const = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_const.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_const.setMaximumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_const.setObjectName(_fromUtf8("swp_inp_coeff_const"))
        self.verticalLayout_12.addWidget(self.swp_inp_coeff_const)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.swp_lbl_coeff_0 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_0.setEnabled(True)
        self.swp_lbl_coeff_0.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_0.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_0.setReadOnly(True)
        self.swp_lbl_coeff_0.setObjectName(_fromUtf8("swp_lbl_coeff_0"))
        self.verticalLayout_16.addWidget(self.swp_lbl_coeff_0)
        self.swp_inp_coeff_0 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_0.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_0.setMaximumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_0.setObjectName(_fromUtf8("swp_inp_coeff_0"))
        self.verticalLayout_16.addWidget(self.swp_inp_coeff_0)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.swp_lbl_coeff_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_1.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_1.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_1.setReadOnly(True)
        self.swp_lbl_coeff_1.setObjectName(_fromUtf8("swp_lbl_coeff_1"))
        self.verticalLayout_15.addWidget(self.swp_lbl_coeff_1)
        self.swp_inp_coeff_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_1.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_1.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_inp_coeff_1.setObjectName(_fromUtf8("swp_inp_coeff_1"))
        self.verticalLayout_15.addWidget(self.swp_inp_coeff_1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_15)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.swp_lbl_coeff_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_2.setMaximumSize(QtCore.QSize(99, 16777215))
        self.swp_lbl_coeff_2.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_2.setReadOnly(True)
        self.swp_lbl_coeff_2.setObjectName(_fromUtf8("swp_lbl_coeff_2"))
        self.verticalLayout_18.addWidget(self.swp_lbl_coeff_2)
        self.swp_inp_coeff_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_2.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_2.setMaximumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_2.setObjectName(_fromUtf8("swp_inp_coeff_2"))
        self.verticalLayout_18.addWidget(self.swp_inp_coeff_2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.swp_lbl_coeff_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_3.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_3.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_3.setReadOnly(True)
        self.swp_lbl_coeff_3.setObjectName(_fromUtf8("swp_lbl_coeff_3"))
        self.verticalLayout_19.addWidget(self.swp_lbl_coeff_3)
        self.swp_inp_coeff_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_3.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_3.setMaximumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_3.setObjectName(_fromUtf8("swp_inp_coeff_3"))
        self.verticalLayout_19.addWidget(self.swp_inp_coeff_3)
        self.horizontalLayout_16.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.swp_lbl_coeff_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_4.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_4.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_4.setReadOnly(True)
        self.swp_lbl_coeff_4.setObjectName(_fromUtf8("swp_lbl_coeff_4"))
        self.verticalLayout_20.addWidget(self.swp_lbl_coeff_4)
        self.swp_inp_coeff_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_4.setMinimumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_4.setMaximumSize(QtCore.QSize(98, 20))
        self.swp_inp_coeff_4.setReadOnly(False)
        self.swp_inp_coeff_4.setObjectName(_fromUtf8("swp_inp_coeff_4"))
        self.verticalLayout_20.addWidget(self.swp_inp_coeff_4)
        self.horizontalLayout_16.addLayout(self.verticalLayout_20)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.swp_lbl_coeff_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_lbl_coeff_5.setMaximumSize(QtCore.QSize(98, 16777215))
        self.swp_lbl_coeff_5.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.swp_lbl_coeff_5.setReadOnly(True)
        self.swp_lbl_coeff_5.setObjectName(_fromUtf8("swp_lbl_coeff_5"))
        self.verticalLayout_17.addWidget(self.swp_lbl_coeff_5)
        self.swp_inp_coeff_5 = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.swp_inp_coeff_5.setMinimumSize(QtCore.QSize(99, 0))
        self.swp_inp_coeff_5.setMaximumSize(QtCore.QSize(99, 20))
        self.swp_inp_coeff_5.setObjectName(_fromUtf8("swp_inp_coeff_5"))
        self.verticalLayout_17.addWidget(self.swp_inp_coeff_5)
        self.horizontalLayout_16.addLayout(self.verticalLayout_17)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.verticalLayout_21.addLayout(self.verticalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_21)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 3)
        self.horizontalLayoutWidget_13 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 370, 951, 161))
        self.horizontalLayoutWidget_13.setObjectName(_fromUtf8("horizontalLayoutWidget_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.red_lbl_settings = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.red_lbl_settings.setReadOnly(True)
        self.red_lbl_settings.setObjectName(_fromUtf8("red_lbl_settings"))
        self.horizontalLayout_18.addWidget(self.red_lbl_settings)
        self.rec_btn_add = QtGui.QPushButton(self.horizontalLayoutWidget_13)
        self.rec_btn_add.setObjectName(_fromUtf8("rec_btn_add"))
        self.horizontalLayout_18.addWidget(self.rec_btn_add)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_18)
        self.rec_list_settings = QtGui.QListWidget(self.horizontalLayoutWidget_13)
        self.rec_list_settings.setObjectName(_fromUtf8("rec_list_settings"))
        self.verticalLayout_22.addWidget(self.rec_list_settings)
        self.rec_btn_del = QtGui.QPushButton(self.horizontalLayoutWidget_13)
        self.rec_btn_del.setObjectName(_fromUtf8("rec_btn_del"))
        self.verticalLayout_22.addWidget(self.rec_btn_del)
        self.horizontalLayout_17.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.rec_inp_label = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_inp_label.setObjectName(_fromUtf8("rec_inp_label"))
        self.verticalLayout_24.addWidget(self.rec_inp_label)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.rec_lbl_type = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_type.setReadOnly(True)
        self.rec_lbl_type.setObjectName(_fromUtf8("rec_lbl_type"))
        self.horizontalLayout_20.addWidget(self.rec_lbl_type)
        self.rec_dd_type = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_type.setObjectName(_fromUtf8("rec_dd_type"))
        self.rec_dd_type.addItem(_fromUtf8(""))
        self.rec_dd_type.addItem(_fromUtf8(""))
        self.rec_dd_type.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.rec_dd_type)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_20)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem9)
        self.rec_lbl_builtins = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_builtins.setReadOnly(True)
        self.rec_lbl_builtins.setObjectName(_fromUtf8("rec_lbl_builtins"))
        self.verticalLayout_24.addWidget(self.rec_lbl_builtins)
        self.rec_dd_builtins = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_builtins.setObjectName(_fromUtf8("rec_dd_builtins"))
        self.verticalLayout_24.addWidget(self.rec_dd_builtins)
        self.horizontalLayout_19.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.rec_lbl_vds = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_vds.setReadOnly(True)
        self.rec_lbl_vds.setObjectName(_fromUtf8("rec_lbl_vds"))
        self.verticalLayout_25.addWidget(self.rec_lbl_vds)
        self.rec_dd_vds = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_vds.setObjectName(_fromUtf8("rec_dd_vds"))
        self.verticalLayout_25.addWidget(self.rec_dd_vds)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.rec_lbl_vds_name = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_vds_name.setReadOnly(True)
        self.rec_lbl_vds_name.setObjectName(_fromUtf8("rec_lbl_vds_name"))
        self.horizontalLayout_21.addWidget(self.rec_lbl_vds_name)
        self.rec_inp_vds_name = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_inp_vds_name.setObjectName(_fromUtf8("rec_inp_vds_name"))
        self.horizontalLayout_21.addWidget(self.rec_inp_vds_name)
        self.verticalLayout_25.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.rec_lbl_vds_id = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_vds_id.setReadOnly(True)
        self.rec_lbl_vds_id.setObjectName(_fromUtf8("rec_lbl_vds_id"))
        self.horizontalLayout_22.addWidget(self.rec_lbl_vds_id)
        self.rec_inp_vds_id = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_inp_vds_id.setObjectName(_fromUtf8("rec_inp_vds_id"))
        self.horizontalLayout_22.addWidget(self.rec_inp_vds_id)
        self.verticalLayout_25.addLayout(self.horizontalLayout_22)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem10)
        self.horizontalLayout_19.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.rec_lbl_rad = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_rad.setReadOnly(True)
        self.rec_lbl_rad.setObjectName(_fromUtf8("rec_lbl_rad"))
        self.verticalLayout_26.addWidget(self.rec_lbl_rad)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.rec_lbl_rad_server = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_rad_server.setReadOnly(True)
        self.rec_lbl_rad_server.setObjectName(_fromUtf8("rec_lbl_rad_server"))
        self.verticalLayout_27.addWidget(self.rec_lbl_rad_server)
        self.rec_lbl_rad_device = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_rad_device.setReadOnly(True)
        self.rec_lbl_rad_device.setObjectName(_fromUtf8("rec_lbl_rad_device"))
        self.verticalLayout_27.addWidget(self.rec_lbl_rad_device)
        self.rec_lbl_rad_setting = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_rad_setting.setReadOnly(True)
        self.rec_lbl_rad_setting.setObjectName(_fromUtf8("rec_lbl_rad_setting"))
        self.verticalLayout_27.addWidget(self.rec_lbl_rad_setting)
        self.horizontalLayout_23.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.rec_dd_rad_server = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_rad_server.setObjectName(_fromUtf8("rec_dd_rad_server"))
        self.verticalLayout_28.addWidget(self.rec_dd_rad_server)
        self.rec_dd_rad_device = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_rad_device.setObjectName(_fromUtf8("rec_dd_rad_device"))
        self.verticalLayout_28.addWidget(self.rec_dd_rad_device)
        self.rec_dd_rad_setting = QtGui.QComboBox(self.horizontalLayoutWidget_13)
        self.rec_dd_rad_setting.setObjectName(_fromUtf8("rec_dd_rad_setting"))
        self.verticalLayout_28.addWidget(self.rec_dd_rad_setting)
        self.horizontalLayout_23.addLayout(self.verticalLayout_28)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 3)
        self.verticalLayout_26.addLayout(self.horizontalLayout_23)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem11)
        self.horizontalLayout_19.addLayout(self.verticalLayout_26)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.rec_lbl_rad_input_req = QtGui.QTextEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_rad_input_req.setReadOnly(True)
        self.rec_lbl_rad_input_req.setObjectName(_fromUtf8("rec_lbl_rad_input_req"))
        self.horizontalLayout_24.addWidget(self.rec_lbl_rad_input_req)
        self.verticalLayout_29.addLayout(self.horizontalLayout_24)
        self.rec_lay_rad_inp = QtGui.QVBoxLayout()
        self.rec_lay_rad_inp.setSpacing(0)
        self.rec_lay_rad_inp.setObjectName(_fromUtf8("rec_lay_rad_inp"))
        self.verticalLayout_29.addLayout(self.rec_lay_rad_inp)
        self.rec_btn_rad_set_inputs = QtGui.QPushButton(self.horizontalLayoutWidget_13)
        self.rec_btn_rad_set_inputs.setObjectName(_fromUtf8("rec_btn_rad_set_inputs"))
        self.verticalLayout_29.addWidget(self.rec_btn_rad_set_inputs)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem12)
        self.horizontalLayout_19.addLayout(self.verticalLayout_29)
        self.horizontalLayout_19.setStretch(0, 3)
        self.horizontalLayout_19.setStretch(1, 3)
        self.horizontalLayout_19.setStretch(2, 3)
        self.horizontalLayout_19.setStretch(3, 4)
        self.verticalLayout_23.addLayout(self.horizontalLayout_19)
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.rec_lbl_ignore = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.rec_lbl_ignore.setReadOnly(True)
        self.rec_lbl_ignore.setObjectName(_fromUtf8("rec_lbl_ignore"))
        self.horizontalLayout_25.addWidget(self.rec_lbl_ignore)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 6)
        self.verticalLayout_30.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(12)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.rec_cb_ignore_0 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_0.setObjectName(_fromUtf8("rec_cb_ignore_0"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_0)
        self.rec_cb_ignore_1 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_1.setObjectName(_fromUtf8("rec_cb_ignore_1"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_1)
        self.rec_cb_ignore_2 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_2.setObjectName(_fromUtf8("rec_cb_ignore_2"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_2)
        self.rec_cb_ignore_3 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_3.setObjectName(_fromUtf8("rec_cb_ignore_3"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_3)
        self.rec_cb_ignore_4 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_4.setObjectName(_fromUtf8("rec_cb_ignore_4"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_4)
        self.rec_cb_ignore_5 = QtGui.QCheckBox(self.horizontalLayoutWidget_13)
        self.rec_cb_ignore_5.setObjectName(_fromUtf8("rec_cb_ignore_5"))
        self.horizontalLayout_26.addWidget(self.rec_cb_ignore_5)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem14)
        self.rec_btn_ignore_all = QtGui.QPushButton(self.horizontalLayoutWidget_13)
        self.rec_btn_ignore_all.setChecked(False)
        self.rec_btn_ignore_all.setObjectName(_fromUtf8("rec_btn_ignore_all"))
        self.horizontalLayout_26.addWidget(self.rec_btn_ignore_all)
        self.verticalLayout_30.addLayout(self.horizontalLayout_26)
        self.verticalLayout_23.addLayout(self.verticalLayout_30)
        self.horizontalLayout_17.addLayout(self.verticalLayout_23)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 3)
        self.verticalLayoutWidget_19 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(680, 0, 273, 151))
        self.verticalLayoutWidget_19.setObjectName(_fromUtf8("verticalLayoutWidget_19"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.status_lbl_status = QtGui.QLineEdit(self.verticalLayoutWidget_19)
        self.status_lbl_status.setText(_fromUtf8(""))
        self.status_lbl_status.setReadOnly(True)
        self.status_lbl_status.setObjectName(_fromUtf8("status_lbl_status"))
        self.horizontalLayout_31.addWidget(self.status_lbl_status)
        self.status_btn_start = QtGui.QPushButton(self.verticalLayoutWidget_19)
        self.status_btn_start.setObjectName(_fromUtf8("status_btn_start"))
        self.horizontalLayout_31.addWidget(self.status_btn_start)
        self.verticalLayout_31.addLayout(self.horizontalLayout_31)
        self.status_list_issues = QtGui.QListWidget(self.verticalLayoutWidget_19)
        self.status_list_issues.setObjectName(_fromUtf8("status_list_issues"))
        self.verticalLayout_31.addWidget(self.status_list_issues)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dv_inp_location = QtGui.QLineEdit(self.verticalLayoutWidget_19)
        self.dv_inp_location.setObjectName(_fromUtf8("dv_inp_location"))
        self.horizontalLayout_4.addWidget(self.dv_inp_location)
        self.dv_inp_filename = QtGui.QLineEdit(self.verticalLayoutWidget_19)
        self.dv_inp_filename.setObjectName(_fromUtf8("dv_inp_filename"))
        self.horizontalLayout_4.addWidget(self.dv_inp_filename)
        self.verticalLayout_31.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.status_cb_start_paused = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.status_cb_start_paused.setObjectName(_fromUtf8("status_cb_start_paused"))
        self.horizontalLayout_5.addWidget(self.status_cb_start_paused)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.cb_no_log = QtGui.QCheckBox(self.verticalLayoutWidget_19)
        self.cb_no_log.setObjectName(_fromUtf8("cb_no_log"))
        self.horizontalLayout_5.addWidget(self.cb_no_log)
        self.verticalLayout_31.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_22 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(0, 550, 571, 193))
        self.verticalLayoutWidget_22.setObjectName(_fromUtf8("verticalLayoutWidget_22"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.com_lbl_comments = QtGui.QLineEdit(self.verticalLayoutWidget_22)
        self.com_lbl_comments.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.com_lbl_comments.setReadOnly(True)
        self.com_lbl_comments.setObjectName(_fromUtf8("com_lbl_comments"))
        self.verticalLayout_34.addWidget(self.com_lbl_comments)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.com_inp_body = QtGui.QTextEdit(self.verticalLayoutWidget_22)
        self.com_inp_body.setAcceptRichText(False)
        self.com_inp_body.setObjectName(_fromUtf8("com_inp_body"))
        self.verticalLayout_32.addWidget(self.com_inp_body)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.com_inp_author = QtGui.QLineEdit(self.verticalLayoutWidget_22)
        self.com_inp_author.setObjectName(_fromUtf8("com_inp_author"))
        self.horizontalLayout_27.addWidget(self.com_inp_author)
        self.com_btn_add = QtGui.QPushButton(self.verticalLayoutWidget_22)
        self.com_btn_add.setObjectName(_fromUtf8("com_btn_add"))
        self.horizontalLayout_27.addWidget(self.com_btn_add)
        self.verticalLayout_32.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.com_lbl_format = QtGui.QLineEdit(self.verticalLayoutWidget_22)
        self.com_lbl_format.setObjectName(_fromUtf8("com_lbl_format"))
        self.horizontalLayout_28.addWidget(self.com_lbl_format)
        self.verticalLayout_33.addLayout(self.horizontalLayout_28)
        self.com_list_comments = QtGui.QListWidget(self.verticalLayoutWidget_22)
        self.com_list_comments.setObjectName(_fromUtf8("com_list_comments"))
        self.verticalLayout_33.addWidget(self.com_list_comments)
        self.com_btn_del = QtGui.QPushButton(self.verticalLayoutWidget_22)
        self.com_btn_del.setObjectName(_fromUtf8("com_btn_del"))
        self.verticalLayout_33.addWidget(self.com_btn_del)
        self.horizontalLayout_29.addLayout(self.verticalLayout_33)
        self.verticalLayout_34.addLayout(self.horizontalLayout_29)
        self.verticalLayoutWidget_23 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(590, 550, 361, 191))
        self.verticalLayoutWidget_23.setObjectName(_fromUtf8("verticalLayoutWidget_23"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.par_lbl_parameters = QtGui.QLineEdit(self.verticalLayoutWidget_23)
        self.par_lbl_parameters.setStyleSheet(_fromUtf8("QLineEdit { background-color: rgb(224,224,224) }"))
        self.par_lbl_parameters.setReadOnly(True)
        self.par_lbl_parameters.setObjectName(_fromUtf8("par_lbl_parameters"))
        self.verticalLayout_35.addWidget(self.par_lbl_parameters)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.par_inp_name = QtGui.QLineEdit(self.verticalLayoutWidget_23)
        self.par_inp_name.setToolTip(_fromUtf8(""))
        self.par_inp_name.setObjectName(_fromUtf8("par_inp_name"))
        self.horizontalLayout_30.addWidget(self.par_inp_name)
        self.par_inp_units = QtGui.QLineEdit(self.verticalLayoutWidget_23)
        self.par_inp_units.setToolTip(_fromUtf8(""))
        self.par_inp_units.setObjectName(_fromUtf8("par_inp_units"))
        self.horizontalLayout_30.addWidget(self.par_inp_units)
        self.par_inp_value = QtGui.QLineEdit(self.verticalLayoutWidget_23)
        self.par_inp_value.setObjectName(_fromUtf8("par_inp_value"))
        self.horizontalLayout_30.addWidget(self.par_inp_value)
        self.par_btn_add = QtGui.QPushButton(self.verticalLayoutWidget_23)
        self.par_btn_add.setObjectName(_fromUtf8("par_btn_add"))
        self.horizontalLayout_30.addWidget(self.par_btn_add)
        self.verticalLayout_35.addLayout(self.horizontalLayout_30)
        self.par_list_parameters = QtGui.QListWidget(self.verticalLayoutWidget_23)
        self.par_list_parameters.setObjectName(_fromUtf8("par_list_parameters"))
        self.verticalLayout_35.addWidget(self.par_list_parameters)
        self.par_btn_del = QtGui.QPushButton(self.verticalLayoutWidget_23)
        self.par_btn_del.setObjectName(_fromUtf8("par_btn_del"))
        self.verticalLayout_35.addWidget(self.par_btn_del)
        setup.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(setup)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        setup.setStatusBar(self.statusbar)

        self.retranslateUi(setup)
        QtCore.QMetaObject.connectSlotsByName(setup)

    def retranslateUi(self, setup):
        setup.setWindowTitle(_translate("setup", "MainWindow", None))
        self.axes_lbl_priority.setText(_translate("setup", "Priority", None))
        self.axes_lbl_name.setText(_translate("setup", "Name", None))
        self.axes_lbl_start.setText(_translate("setup", "Start", None))
        self.axes_lbl_stop.setText(_translate("setup", "Stop", None))
        self.axes_lbl_points.setText(_translate("setup", "Points", None))
        self.lineEdit.setText(_translate("setup", "Delay (ms)", None))
        self.axes_btn_add.setText(_translate("setup", "Add Axis", None))
        self.swp_lbl_settings.setText(_translate("setup", "Swept Settings", None))
        self.swp_btn_add.setText(_translate("setup", "Add Swept Setting", None))
        self.swp_btn_del.setText(_translate("setup", "Delete Selected Setting", None))
        self.swp_inp_label.setPlaceholderText(_translate("setup", "Label", None))
        self.swp_lbl_type.setText(_translate("setup", "Type", None))
        self.swp_dd_type.setItemText(0, _translate("setup", "VDS", None))
        self.swp_dd_type.setItemText(1, _translate("setup", "LabRAD", None))
        self.swp_dd_type.setItemText(2, _translate("setup", "Builtin", None))
        self.swp_lbl_builtins.setText(_translate("setup", "Builtin list", None))
        self.swp_lbl_vds.setText(_translate("setup", "VDS specifications", None))
        self.swp_lbl_vds_name.setText(_translate("setup", "Name", None))
        self.swp_lbl_vds_id.setText(_translate("setup", "ID", None))
        self.swp_lbl_rad.setText(_translate("setup", "LabRAD specifications", None))
        self.swp_lbl_rad_server.setText(_translate("setup", "Server", None))
        self.swp_lbl_rad_device.setText(_translate("setup", "Device", None))
        self.swp_lbl_rad_setting.setText(_translate("setup", "Setting", None))
        self.swp_btn_rad_set_inputs.setText(_translate("setup", "Set Inputs", None))
        self.swp_lbl_coeff.setText(_translate("setup", "Coefficients", None))
        self.swp_lbl_coeff_const.setText(_translate("setup", "Constant", None))
        self.swp_lbl_coeff_0.setText(_translate("setup", "Axis 0", None))
        self.swp_lbl_coeff_1.setText(_translate("setup", "Axis 1", None))
        self.swp_lbl_coeff_2.setText(_translate("setup", "Axis 2", None))
        self.swp_lbl_coeff_3.setText(_translate("setup", "Axis 3", None))
        self.swp_lbl_coeff_4.setText(_translate("setup", "Axis 4", None))
        self.swp_lbl_coeff_5.setText(_translate("setup", "Axis 5", None))
        self.red_lbl_settings.setText(_translate("setup", "Recorded Settings", None))
        self.rec_btn_add.setText(_translate("setup", "Add Recorded Setting", None))
        self.rec_btn_del.setText(_translate("setup", "Delete Selected Setting", None))
        self.rec_inp_label.setPlaceholderText(_translate("setup", "Label", None))
        self.rec_lbl_type.setText(_translate("setup", "Type", None))
        self.rec_dd_type.setItemText(0, _translate("setup", "VDS", None))
        self.rec_dd_type.setItemText(1, _translate("setup", "LabRAD", None))
        self.rec_dd_type.setItemText(2, _translate("setup", "Builtin", None))
        self.rec_lbl_builtins.setText(_translate("setup", "Builtin list", None))
        self.rec_lbl_vds.setText(_translate("setup", "VDS specifications", None))
        self.rec_lbl_vds_name.setText(_translate("setup", "Name", None))
        self.rec_lbl_vds_id.setText(_translate("setup", "ID", None))
        self.rec_lbl_rad.setText(_translate("setup", "LabRAD specifications", None))
        self.rec_lbl_rad_server.setText(_translate("setup", "Server", None))
        self.rec_lbl_rad_device.setText(_translate("setup", "Device", None))
        self.rec_lbl_rad_setting.setText(_translate("setup", "Setting", None))
        self.rec_btn_rad_set_inputs.setText(_translate("setup", "Set Inputs", None))
        self.rec_lbl_ignore.setText(_translate("setup", "Ignore Axes", None))
        self.rec_cb_ignore_0.setText(_translate("setup", "Axis 0", None))
        self.rec_cb_ignore_1.setText(_translate("setup", "Axis 1", None))
        self.rec_cb_ignore_2.setText(_translate("setup", "Axis 2", None))
        self.rec_cb_ignore_3.setText(_translate("setup", "Axis 3", None))
        self.rec_cb_ignore_4.setText(_translate("setup", "Axis 4", None))
        self.rec_cb_ignore_5.setText(_translate("setup", "Axis 5", None))
        self.rec_btn_ignore_all.setText(_translate("setup", "Ignore All (setting written as parameter)", None))
        self.status_lbl_status.setToolTip(_translate("setup", "<html><head/><body><p>Status of the sweep setup (whether or not the sweep is ready to be started)</p></body></html>", None))
        self.status_lbl_status.setPlaceholderText(_translate("setup", "Setup Status", None))
        self.status_btn_start.setText(_translate("setup", "Start Sweep", None))
        self.status_list_issues.setToolTip(_translate("setup", "<html><head/><body><p>List of issues preventing a sweep from being started</p></body></html>", None))
        self.dv_inp_location.setToolTip(_translate("setup", "<html><head/><body><p>File location in the DataVault directory.</p><p>Subfolders should be separated by backslashes ( \\ )</p><p>Example:</p><p>capacitance\\2017\\may</p></body></html>", None))
        self.dv_inp_location.setPlaceholderText(_translate("setup", "DataVault file location", None))
        self.dv_inp_filename.setToolTip(_translate("setup", "<html><head/><body><p>File name of DataVault log for this sweep</p></body></html>", None))
        self.dv_inp_filename.setPlaceholderText(_translate("setup", "DataVault file name", None))
        self.status_cb_start_paused.setToolTip(_translate("setup", "<html><head/><body><p>If this is checked, the sweep will be created but not start taking data or changing settings until it is manually un-paused.</p></body></html>", None))
        self.status_cb_start_paused.setText(_translate("setup", "Start Paused", None))
        self.cb_no_log.setToolTip(_translate("setup", "<html><head/><body><p>If this box is checked, no DataVault file will be created for this sweep, and the data created will not be logged anywhere.</p><p>This is intended to be used on sweeps for testing purposes.</p></body></html>", None))
        self.cb_no_log.setText(_translate("setup", "Do not log", None))
        self.com_lbl_comments.setText(_translate("setup", "Comments", None))
        self.com_inp_author.setPlaceholderText(_translate("setup", "Comment author", None))
        self.com_btn_add.setText(_translate("setup", "Add Comment", None))
        self.com_lbl_format.setText(_translate("setup", "(Author) - Comment Body", None))
        self.com_list_comments.setToolTip(_translate("setup", "List of comments. Format is (Author) - Comment body", None))
        self.com_btn_del.setText(_translate("setup", "Delete Selected Comment", None))
        self.par_lbl_parameters.setText(_translate("setup", "Parameters", None))
        self.par_inp_name.setPlaceholderText(_translate("setup", "Name", None))
        self.par_inp_units.setPlaceholderText(_translate("setup", "Units", None))
        self.par_inp_value.setPlaceholderText(_translate("setup", "Value", None))
        self.par_btn_add.setText(_translate("setup", "Add Parameter", None))
        self.par_btn_del.setText(_translate("setup", "Delete Selected Parameter", None))

